### ISSUE TITLE
SPA can't be loaded from a domain other than localhost:8080

### ISSUE THREAD

**Issue by TimonLukas** [IBM/application-modernization-javaee-quarkus#13]
Currently it's not possible to show this demo from a domain other than `localhost` because the frontend scripts are hardcoded to that URL (I think because of [this](https://github.com/IBM/application-modernization-javaee-quarkus/blob/master/frontend-single-spa/shell/src/index.ejs)). Can this be changed to load dynamically from the current location?

**Comment by nheidloff** [comment]
As discussed this is more than using a relative URL since different ports are used. The URLs would have to be changed, for example how I do this in the scripts when deploying to OpenShift.

Right now I don't have time to do this.
